version = 0.1
[default.deploy.parameters]
stack_name = "ecommerce"
resolve_s3 = true
s3_prefix = "ecommerce"
region = "us-east-1"
profile = "eventuser"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
